from medicore.core.ui_schema import ColumnDef, EntitySchema, FieldDef, FilterDef

patient_schema = EntitySchema(
    entity_name="patient",
    title="Patient",
    plural_title="Patients",
    endpoint_prefix="/patients",
    default_sort="-created_at",
    duplicate_check_fields=["phone", "first_name", "last_name", "date_of_birth"],
    searchable_fields=["mrn", "first_name", "last_name", "phone", "email"],
    fields=[
        FieldDef(
            name="mrn",
            label="MRN",
            field_type="string",
            required=False,
            placeholder="Auto-generated on creation",
            help_text="Unique Medical Record Number",
            grid_col_span=1,
        ),
        FieldDef(
            name="status",
            label="Patient Status",
            field_type="select",
            required=True,
            options=["Active", "Inpatient", "Discharged", "Critical"],
            default="Active",
            grid_col_span=1,
            badge_colors={
                "Active": "bg-emerald-50 text-emerald-700 border-emerald-200 dark:bg-emerald-950/50 dark:text-emerald-400 dark:border-emerald-800",
                "Inpatient": "bg-sky-50 text-sky-700 border-sky-200 dark:bg-sky-950/50 dark:text-sky-400 dark:border-sky-800",
                "Critical": "bg-rose-50 text-rose-700 border-rose-200 dark:bg-rose-950/50 dark:text-rose-400 dark:border-rose-800",
                "Discharged": "bg-slate-100 text-slate-700 border-slate-200 dark:bg-slate-800 dark:text-slate-400 dark:border-slate-700",
            },
        ),
        FieldDef(
            name="first_name",
            label="First Name",
            field_type="string",
            required=True,
            placeholder="e.g. Eleanor",
            grid_col_span=1,
        ),
        FieldDef(
            name="last_name",
            label="Last Name",
            field_type="string",
            required=True,
            placeholder="e.g. Vance",
            grid_col_span=1,
        ),
        FieldDef(
            name="date_of_birth",
            label="Date of Birth",
            field_type="date",
            required=True,
            placeholder="YYYY-MM-DD",
            grid_col_span=1,
        ),
        FieldDef(
            name="gender",
            label="Gender",
            field_type="select",
            required=True,
            options=["Male", "Female", "Other"],
            default="Female",
            grid_col_span=1,
        ),
        FieldDef(
            name="blood_group",
            label="Blood Group",
            field_type="select",
            required=False,
            options=["A+", "A-", "B+", "B-", "AB+", "AB-", "O+", "O-"],
            grid_col_span=1,
        ),
        FieldDef(
            name="phone",
            label="Phone Number",
            field_type="string",
            required=True,
            placeholder="+1 (555) 000-0000",
            help_text="Used for duplicate validation and SMS appointment alerts",
            grid_col_span=1,
        ),
        FieldDef(
            name="email",
            label="Email Address",
            field_type="string",
            required=False,
            placeholder="eleanor.vance@example.com",
            grid_col_span=2,
        ),
        FieldDef(
            name="allergies",
            label="Allergies & Adverse Reactions",
            field_type="text",
            required=False,
            placeholder="e.g. Penicillin, Latex, Peanuts",
            help_text="Critical clinical alert for prescribing clinicians",
            grid_col_span=2,
        ),
        FieldDef(
            name="address",
            label="Residential Address",
            field_type="text",
            required=False,
            placeholder="Street address, City, State, ZIP",
            grid_col_span=2,
        ),
        FieldDef(
            name="emergency_contact_name",
            label="Emergency Contact Name",
            field_type="string",
            required=False,
            placeholder="Next of kin / guardian",
            grid_col_span=1,
        ),
        FieldDef(
            name="emergency_contact_phone",
            label="Emergency Contact Phone",
            field_type="string",
            required=False,
            placeholder="+1 (555) 999-9999",
            grid_col_span=1,
        ),
    ],
    list_columns=[
        ColumnDef(field_name="mrn", label="MRN", sortable=True, width="w-28", formatter="mrn"),
        ColumnDef(field_name="full_name", label="Patient Name", sortable=True, width="w-44"),
        ColumnDef(field_name="date_of_birth", label="DOB", sortable=True, width="w-24", formatter="date"),
        ColumnDef(field_name="gender", label="Gender", sortable=True, width="w-20"),
        ColumnDef(field_name="blood_group", label="Blood", sortable=True, width="w-16", formatter="badge"),
        ColumnDef(field_name="phone", label="Phone", sortable=False, width="w-32"),
        ColumnDef(
            field_name="status",
            label="Status",
            sortable=True,
            width="w-24",
            formatter="badge",
            badge_map={
                "Active": "bg-emerald-50 text-emerald-700 border-emerald-200 dark:bg-emerald-950/40 dark:text-emerald-300 dark:border-emerald-800",
                "Inpatient": "bg-sky-50 text-sky-700 border-sky-200 dark:bg-sky-950/40 dark:text-sky-300 dark:border-sky-800",
                "Critical": "bg-rose-50 text-rose-700 border-rose-200 dark:bg-rose-950/40 dark:text-rose-300 dark:border-rose-800",
                "Discharged": "bg-slate-100 text-slate-700 border-slate-200 dark:bg-slate-800 dark:text-slate-400 dark:border-slate-700",
            },
        ),
    ],
    filters=[
        FilterDef(field_name="status", label="Status", filter_type="select", options=["Active", "Inpatient", "Discharged", "Critical"]),
        FilterDef(field_name="gender", label="Gender", filter_type="select", options=["Male", "Female", "Other"]),
        FilterDef(field_name="blood_group", label="Blood Group", filter_type="select", options=["A+", "A-", "B+", "B-", "AB+", "AB-", "O+", "O-"]),
    ],
)
