from medicore.core.ui_schema import ColumnDef, EntitySchema, FieldDef, FilterDef

item_schema = EntitySchema(
    entity_name="pharmacy_item",
    title="Pharmacy Item",
    plural_title="Pharmacy Items",
    endpoint_prefix="/pharmacy/inventory",
    default_sort="name",
    searchable_fields=["code", "name", "generic_name", "brand_name", "category"],
    fields=[
        FieldDef(name="code", label="Item Code / SKU", field_type="string", required=True, placeholder="e.g. MED-00101"),
        FieldDef(name="name", label="Item Name", field_type="string", required=True, placeholder="e.g. Amoxicillin 500mg Capsule"),
        FieldDef(name="generic_name", label="Generic Name", field_type="string", required=True, placeholder="e.g. Amoxicillin"),
        FieldDef(name="brand_name", label="Brand Name", field_type="string", required=False, placeholder="e.g. Amoxil"),
        FieldDef(
            name="category",
            label="Therapeutic Category",
            field_type="select",
            required=True,
            options=[
                "Antibiotics",
                "Analgesics & Pain",
                "Cardiovascular",
                "Endocrine & Diabetes",
                "Respiratory",
                "Gastrointestinal",
                "CNS & Psychiatric",
                "IV Fluids & Electrolytes",
                "Surgical & Medical Consumables",
                "Dermatology & Topicals",
                "Ophthalmic & Otic",
                "Vitamins & Nutrition",
            ],
        ),
        FieldDef(name="form", label="Dosage Form", field_type="string", required=True, default="Tablet"),
        FieldDef(name="strength", label="Strength", field_type="string", required=False, placeholder="e.g. 500 mg"),
        FieldDef(name="unit", label="Dispense Unit", field_type="string", required=True, default="Tablet"),
        FieldDef(name="cost_price", label="Cost Price ($)", field_type="number", required=True, default=0.0),
        FieldDef(name="unit_price", label="Selling Price / MRP ($)", field_type="number", required=True, default=0.0),
        FieldDef(name="reorder_level", label="Reorder Level", field_type="number", required=True, default=50),
        FieldDef(name="reorder_quantity", label="Reorder Quantity", field_type="number", required=True, default=150),
        FieldDef(name="is_prescription_required", label="Prescription Required", field_type="boolean", default=True),
        FieldDef(name="is_active", label="Active Item", field_type="boolean", default=True),
    ],
    list_columns=[
        ColumnDef(field_name="code", label="SKU / Code"),
        ColumnDef(field_name="name", label="Drug / Item Name"),
        ColumnDef(field_name="generic_name", label="Generic Name"),
        ColumnDef(field_name="category", label="Category", formatter="badge"),
        ColumnDef(field_name="unit_price", label="MRP ($)", formatter="currency"),
        ColumnDef(field_name="reorder_level", label="Reorder Lvl"),
    ],
    filters=[
        FilterDef(
            field_name="category",
            label="Category",
            filter_type="select",
            options=[
                "Antibiotics",
                "Analgesics & Pain",
                "Cardiovascular",
                "Endocrine & Diabetes",
                "Respiratory",
                "Gastrointestinal",
                "CNS & Psychiatric",
                "IV Fluids & Electrolytes",
                "Surgical & Medical Consumables",
                "Dermatology & Topicals",
                "Ophthalmic & Otic",
                "Vitamins & Nutrition",
            ],
        ),
        FilterDef(field_name="is_prescription_required", label="Rx Required", filter_type="boolean"),
    ],
)

dispense_schema = EntitySchema(
    entity_name="dispense",
    title="Dispense Order",
    plural_title="Dispense Orders",
    endpoint_prefix="/pharmacy/dispenses",
    default_sort="-created_at",
    searchable_fields=["dispense_no", "patient_name", "patient_mrn", "doctor_name"],
    fields=[
        FieldDef(name="dispense_no", label="Dispense #", field_type="string", required=True),
        FieldDef(name="patient_name", label="Patient Name", field_type="string", required=True),
        FieldDef(name="patient_mrn", label="Patient MRN", field_type="string", required=False),
        FieldDef(name="doctor_name", label="Prescribing Doctor", field_type="string", required=False),
        FieldDef(
            name="status",
            label="Status",
            field_type="select",
            required=True,
            options=["pending", "in_progress", "dispensed", "partial", "rejected"],
            badge_colors={
                "pending": "bg-amber-50 text-amber-700 border-amber-200 dark:bg-amber-950/50 dark:text-amber-400 dark:border-amber-800",
                "in_progress": "bg-sky-50 text-sky-700 border-sky-200 dark:bg-sky-950/50 dark:text-sky-400 dark:border-sky-800",
                "dispensed": "bg-emerald-50 text-emerald-700 border-emerald-200 dark:bg-emerald-950/50 dark:text-emerald-400 dark:border-emerald-800",
                "partial": "bg-purple-50 text-purple-700 border-purple-200 dark:bg-purple-950/50 dark:text-purple-400 dark:border-purple-800",
                "rejected": "bg-rose-50 text-rose-700 border-rose-200 dark:bg-rose-950/50 dark:text-rose-400 dark:border-rose-800",
            },
        ),
        FieldDef(name="total_amount", label="Total ($)", field_type="number", default=0.0),
    ],
    list_columns=[
        ColumnDef(field_name="dispense_no", label="Dispense #"),
        ColumnDef(field_name="patient_name", label="Patient"),
        ColumnDef(field_name="patient_mrn", label="MRN"),
        ColumnDef(field_name="doctor_name", label="Doctor"),
        ColumnDef(field_name="status", label="Status", formatter="badge"),
        ColumnDef(field_name="total_amount", label="Total Amount", formatter="currency"),
        ColumnDef(field_name="created_at", label="Created At", formatter="datetime"),
    ],
    filters=[
        FilterDef(
            field_name="status",
            label="Dispense Status",
            filter_type="select",
            options=["pending", "in_progress", "dispensed", "partial", "rejected"],
        ),
        FilterDef(
            field_name="dispense_type",
            label="Type",
            filter_type="select",
            options=["prescription", "counter_otc"],
        ),
    ],
)

supplier_schema = EntitySchema(
    entity_name="supplier",
    title="Pharmaceutical Supplier",
    plural_title="Suppliers",
    endpoint_prefix="/pharmacy/suppliers",
    default_sort="name",
    searchable_fields=["code", "name", "contact_person", "email", "phone"],
    fields=[
        FieldDef(name="code", label="Supplier Code", field_type="string", required=True),
        FieldDef(name="name", label="Company Name", field_type="string", required=True),
        FieldDef(name="contact_person", label="Contact Person", field_type="string"),
        FieldDef(name="phone", label="Phone", field_type="string"),
        FieldDef(name="email", label="Email", field_type="string"),
        FieldDef(name="payment_terms", label="Payment Terms", field_type="string", default="Net 30"),
    ],
    list_columns=[
        ColumnDef(field_name="code", label="Code"),
        ColumnDef(field_name="name", label="Supplier Name"),
        ColumnDef(field_name="contact_person", label="Contact"),
        ColumnDef(field_name="phone", label="Phone"),
        ColumnDef(field_name="payment_terms", label="Terms"),
    ],
)
