from medicore.core.ui_schema import ColumnDef, EntitySchema, FieldDef, FilterDef

appointment_schema = EntitySchema(
    entity_name="appointment",
    title="Appointment",
    plural_title="Appointments",
    endpoint_prefix="/appointments",
    default_sort="-start_datetime",
    searchable_fields=["patient_name", "patient_mrn", "doctor_name", "department", "notes"],
    fields=[
        FieldDef(
            name="patient_name",
            label="Patient Name",
            field_type="string",
            required=True,
            placeholder="Select or enter patient",
            grid_col_span=1,
        ),
        FieldDef(
            name="patient_mrn",
            label="Patient MRN",
            field_type="string",
            required=True,
            placeholder="e.g. MC-2026-00001",
            grid_col_span=1,
        ),
        FieldDef(
            name="doctor_name",
            label="Attending Doctor",
            field_type="string",
            required=True,
            placeholder="Select doctor",
            grid_col_span=1,
        ),
        FieldDef(
            name="department",
            label="Department",
            field_type="select",
            required=True,
            options=["Cardiology", "Neurology", "Pediatrics", "Orthopedics", "General Medicine"],
            default="General Medicine",
            grid_col_span=1,
        ),
        FieldDef(
            name="appointment_date",
            label="Date",
            field_type="date",
            required=True,
            placeholder="YYYY-MM-DD",
            grid_col_span=1,
        ),
        FieldDef(
            name="start_time",
            label="Start Time",
            field_type="string",
            required=True,
            placeholder="HH:MM",
            grid_col_span=1,
        ),
        FieldDef(
            name="end_time",
            label="End Time",
            field_type="string",
            required=True,
            placeholder="HH:MM",
            grid_col_span=1,
        ),
        FieldDef(
            name="type",
            label="Appointment Type",
            field_type="select",
            required=True,
            options=["Consultation", "Follow-up", "Emergency", "Routine Checkup", "Walk-in"],
            default="Consultation",
            grid_col_span=1,
        ),
        FieldDef(
            name="status",
            label="Status",
            field_type="select",
            required=True,
            options=["Booked", "Checked-in", "In-Consultation", "Completed", "Cancelled", "No-show"],
            default="Booked",
            grid_col_span=1,
            badge_colors={
                "Booked": "bg-sky-50 text-sky-700 border-sky-200 dark:bg-sky-950/50 dark:text-sky-400 dark:border-sky-800",
                "Checked-in": "bg-amber-50 text-amber-700 border-amber-200 dark:bg-amber-950/50 dark:text-amber-400 dark:border-amber-800",
                "In-Consultation": "bg-purple-50 text-purple-700 border-purple-200 dark:bg-purple-950/50 dark:text-purple-400 dark:border-purple-800",
                "Completed": "bg-emerald-50 text-emerald-700 border-emerald-200 dark:bg-emerald-950/50 dark:text-emerald-400 dark:border-emerald-800",
                "Cancelled": "bg-slate-100 text-slate-700 border-slate-200 dark:bg-slate-800 dark:text-slate-400 dark:border-slate-700",
                "No-show": "bg-rose-50 text-rose-700 border-rose-200 dark:bg-rose-950/50 dark:text-rose-400 dark:border-rose-800",
            },
        ),
        FieldDef(
            name="source",
            label="Booking Source",
            field_type="select",
            required=True,
            options=["Reception", "Phone", "Online", "Walk-in", "Referral"],
            default="Reception",
            grid_col_span=1,
        ),
        FieldDef(
            name="notes",
            label="Clinical / Intake Notes",
            field_type="text",
            required=False,
            placeholder="Chief complaint or consultation reason",
            grid_col_span=2,
        ),
    ],
    list_columns=[
        ColumnDef(field_name="appointment_date", label="Date", sortable=True, width="w-24", formatter="date"),
        ColumnDef(field_name="start_time", label="Time", sortable=True, width="w-20"),
        ColumnDef(field_name="patient_name", label="Patient", sortable=True, width="w-36"),
        ColumnDef(field_name="patient_mrn", label="MRN", sortable=True, width="w-28", formatter="mrn"),
        ColumnDef(field_name="doctor_name", label="Doctor", sortable=True, width="w-36"),
        ColumnDef(field_name="department", label="Department", sortable=True, width="w-32"),
        ColumnDef(field_name="type", label="Type", sortable=True, width="w-24"),
        ColumnDef(
            field_name="status",
            label="Status",
            sortable=True,
            width="w-28",
            formatter="badge",
            badge_map={
                "Booked": "bg-sky-50 text-sky-700 border-sky-200 dark:bg-sky-950/40 dark:text-sky-300 dark:border-sky-800",
                "Checked-in": "bg-amber-50 text-amber-700 border-amber-200 dark:bg-amber-950/40 dark:text-amber-300 dark:border-amber-800",
                "In-Consultation": "bg-purple-50 text-purple-700 border-purple-200 dark:bg-purple-950/40 dark:text-purple-300 dark:border-purple-800",
                "Completed": "bg-emerald-50 text-emerald-700 border-emerald-200 dark:bg-emerald-950/40 dark:text-emerald-300 dark:border-emerald-800",
                "Cancelled": "bg-slate-100 text-slate-700 border-slate-200 dark:bg-slate-800 dark:text-slate-400 dark:border-slate-700",
                "No-show": "bg-rose-50 text-rose-700 border-rose-200 dark:bg-rose-950/40 dark:text-rose-300 dark:border-rose-800",
            },
        ),
    ],
    filters=[
        FilterDef(
            field_name="status",
            label="Status",
            filter_type="select",
            options=["Booked", "Checked-in", "In-Consultation", "Completed", "Cancelled", "No-show"],
        ),
        FilterDef(
            field_name="department",
            label="Department",
            filter_type="select",
            options=["Cardiology", "Neurology", "Pediatrics", "Orthopedics", "General Medicine"],
        ),
        FilterDef(
            field_name="type",
            label="Type",
            filter_type="select",
            options=["Consultation", "Follow-up", "Emergency", "Routine Checkup", "Walk-in"],
        ),
    ],
)

doctor_schema = EntitySchema(
    entity_name="doctor",
    title="Doctor",
    plural_title="Doctors",
    endpoint_prefix="/appointments/doctors",
    default_sort="name",
    searchable_fields=["name", "department", "specialty", "room_number"],
    fields=[
        FieldDef(name="name", label="Doctor Name", field_type="string", required=True, grid_col_span=1),
        FieldDef(
            name="department",
            label="Department",
            field_type="select",
            required=True,
            options=["Cardiology", "Neurology", "Pediatrics", "Orthopedics", "General Medicine"],
            grid_col_span=1,
        ),
        FieldDef(name="specialty", label="Specialty", field_type="string", required=False, grid_col_span=1),
        FieldDef(name="room_number", label="Consulting Room", field_type="string", required=False, grid_col_span=1),
        FieldDef(name="slot_length", label="Slot Length (min)", field_type="integer", default=20, grid_col_span=1),
        FieldDef(name="is_active", label="Active Status", field_type="boolean", default=True, grid_col_span=1),
    ],
    list_columns=[
        ColumnDef(field_name="name", label="Doctor", sortable=True, width="w-44"),
        ColumnDef(field_name="department", label="Department", sortable=True, width="w-36"),
        ColumnDef(field_name="specialty", label="Specialty", sortable=True, width="w-36"),
        ColumnDef(field_name="room_number", label="Room", sortable=True, width="w-20"),
        ColumnDef(field_name="slot_length", label="Slot (m)", sortable=False, width="w-20"),
    ],
    filters=[
        FilterDef(
            field_name="department",
            label="Department",
            filter_type="select",
            options=["Cardiology", "Neurology", "Pediatrics", "Orthopedics", "General Medicine"],
        ),
    ],
)
